### PR TITLE
fix: writing Delta table with partitioned inputs

### LINKED ISSUE #836: bug: DeltaWriterExec requires exactly one input partition, got 32
I'm using Sail 0.3.4 and something as simple as the below fails when the folder being referenced has multiple parquet files:

```python
spark.read.parquet('.../sf10_parquet/catalog_returns/') \
            .write.format("delta") \
            .mode("overwrite") \
            .save(".../sail_tpcds_sf10/catalog_returns")
```

`DeltaWriterExec requires exactly one input partition, got 32`

If there's a single file in the parquet folder it works fine. Pretty sure this wasn't an issue in 0.3.3. thx!

### PR DESCRIPTION
**Pull request by linhr**
Fixes #836.

### CODE REVIEW

File: crates/sail-delta-lake/src/delta_format/plan_builder.rs [hunk 1]
```diff
@@ -45,27 +44,14 @@ impl DeltaPlanBuilder {
...
-        let current_plan = self.add_projection_node(current_plan)?;
-
-        // 2. Repartition Node
-        let current_plan = self.add_repartition_node(current_plan)?;
-
-        // 3. Sort Node
-        let current_plan = self.add_sort_node(current_plan)?;
-
-        // 4. Coalesce Partitions Node
-        let current_plan = self.add_coalesce_partitions_node(current_plan)?;
```
Comment (linhr) [inline crates/sail-delta-lake/src/delta_format/plan_builder.rs:60]: I guess explicitly adding the coalesce node may not work since the optimizer could decide to remove it. So we have to define the input distribution requirement in `ExecutionPlan`.
