### PR TITLE
fix: concat function behaviour on some subset of input types

### LINKED ISSUE #646: concat function should be able to take binary strings and other types
in spark, concat behaviour is like this:
1) strings -> string
2) binary strings -> binary string
3) primitive types -> cast to strings and concat as string
4) arrays of the same type -> array
5) arrays of different type -> array of coerced type

1 and 4 are already in the code
2 and 3 can be solved relatively easy
5 is worth it's own issue I suppose

also if any of the arguments is NULL, concat must return NULL, now it just eats NULL and concats other

### PR DESCRIPTION
**Pull request by SparkApplicationMaster**
fix concat behaviour for various types:
binary -> binary (casts to strings and uses string concat but casts result to binary)
primitive (coerce to string) -> string 
string and primitive -> string
any NULL input -> NULL output

passes spark-tests
closes #646 (if it's ok to create another issue about passing input arrays with different but coercible types)

### CODE REVIEW

File: crates/sail-plan/src/extension/function/collection/spark_concat.rs [hunk 1]
```diff
@@ -104,14 +117,79 @@ impl ScalarUDFImpl for SparkConcat {
...
+                number_rows: args.number_rows,
+                return_field: args.return_field,
+            };
+
+            ConcatFunc::new().invoke_with_args(casted_args)
+        }?;
+
+        let concatenated_array = match concatenated {
+            ColumnarValue::Array(arr) => arr,
+            ColumnarValue::Scalar(s) => s.to_array()?, // преобразуем скаляр в массив
```
Comment (linhr) [inline crates/sail-plan/src/extension/function/collection/spark_concat.rs]: I feel this line of code is likely self-explanatory without comment.

```suggestion
            ColumnarValue::Scalar(s) => s.to_array()?,
```

**Review by linhr — APPROVED** [review]
This looks nice!

**Comment by linhr** [comment]
Thanks for having this fix! I applied a minor edit to the code and created #650 for future work.
