### PR TITLE
fix: map_function DataType::Null inputs

### LINKED ISSUE #665: Map creation function: Datatype::Null value and empty map()
1) Map should be able to be empty (Datatype::Null, Datatype::Null):
```python
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("test").getOrCreate()
spark.sql("SELECT map() from values (1), (2), (3)").show()
spark.sql("SELECT map() from values (1), (2), (3)").schema
```
```
+-----+
|map()|
+-----+
|   {}|
|   {}|
|   {}|
+-----+
StructType([StructField('data', MapType(NullType(), NullType(), False), False)])
```
2) Value arrays of map can be of Datatype::Null:
```python
spark.sql("SELECT map(1, null, 2, col1) as data from values (1), (2), (3)").show()
```
```
+-------------------+
|               data|
+-------------------+
|{1 -> NULL, 2 -> 1}|
|{1 -> NULL, 2 -> 2}|
|{1 -> NULL, 2 -> 3}|
+-------------------+
```

### PR DESCRIPTION
**Pull request by SparkApplicationMaster**
1) create empty map()
2) create map(key, NULL, ...)

```python
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("test").getOrCreate()
spark.sql("SELECT map() from values (1), (2), (3)").show()
spark.sql("SELECT map(1, null, 2, col1) as data from values (1), (2), (3)").show()
```
```
+-----+
|map()|
+-----+
|   {}|
|   {}|
|   {}|
+-----+

+-------------------+
|               data|
+-------------------+
|{1 -> NULL, 2 -> 1}|
|{1 -> NULL, 2 -> 2}|
|{1 -> NULL, 2 -> 3}|
+-------------------+
```
closes #665

### CODE REVIEW

File: crates/sail-plan/src/extension/function/map/map_function.rs [hunk 1]
```diff
@@ -111,13 +138,27 @@ impl ScalarUDFImpl for MapFunction {
...
-        if arg_types.values().any(|dt| dt != value_type) {
+        if arg_types
+            .values()
+            .any(|dt| (dt != value_type) && (dt != &DataType::Null))
+        {
+            println!(
+                "VALUE_TYPES: CHOSEN: {:?}, ALL: {:?}",
+                value_type,
+                arg_types.values().collect::<Vec<_>>()
+            );
```
Comment (linhr) [inline crates/sail-plan/src/extension/function/map/map_function.rs]:
```suggestion
```

**Review by linhr — APPROVED** [review]
Nice improvements! Thanks!
